services:
  back_db:
    image: postgres:latest
    volumes:
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/log:/var/log/postgresql
    container_name: back_db
    env_file:
      - .env
    ports:
      - 44434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meta_db_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  auth_service:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./backend:/usr/app
    restart: always
    expose:
      - 8001
    ports:
      - "8001:8001"
    depends_on:
      back_db:
        condition: service_healthy
    command: sh -c "python3 cli.py api"