services:
  back_db:
    image: postgres:latest
    volumes:
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/log:/var/log/postgresql
    container_name: back_db
    env_file:
      - .env
    ports:
      - 44434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meta_db_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  back_dubai_bot:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./backend:/usr/app
    restart: always
    expose:
      - 8001
    ports:
      - "8001:8001"
    depends_on:
      back_db:
        condition: service_healthy
    command: sh -c "python3 cli.py api"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    command: server /data --console-address ":9001"