services:
  redis:
    image: redis:7
    container_name: admin_redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    env_file:
      - .env
    volumes:
      - ./dockerfiles/redis/data:/data
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6371:6379"
    