services:
  postgresdb:
    image: postgres:latest
    volumes:
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/log:/var/log/postgresql
    container_name: postgresdb
    env_file:
      - .env
    ports:
      - 44433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meta_db_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env
    volumes:
      - ./dockerfiles/redis/data:/var/lib/redis/data
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./dockerfiles/elasticsearch/data:/var/lib/elasticsearch/data

  dubai_bot:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./backend:/usr/app
    restart: always
    expose:
      - 8002
    ports:
      - "8002:8002"
    depends_on:
      postgresdb:
        condition: service_healthy
    command: sh -c "python3 main.py"