services:
  postgresdb:
    image: postgres:latest
    container_name: bot_db
    env_file:
      - .env
    ports:
      - "44433:5432"
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    env_file:
      - .env
    volumes:
      - ./dockerfiles/redis/data:/var/lib/redis/data
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./dockerfiles/elasticsearch/data:/var/lib/elasticsearch/data